fileVersion: 1
id: "3"
mappingDefinitions:
  SAMPLE:
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
  WORK:
    database: DATALAKE_DEV
    schema: SQLDB_ETL_SCHEMA
name: Production
type: Environment
